#!/bin/bash
# This hook is run after every virtualenv is activated.

# cd () {
#     if (( $# == 0 ))
#     then
#         builtin cd $VIRTUAL_ENV
#     else
#         builtin cd "$@"
#     fi
# }
# cd
